#! /bin/bash
# this is about case script for choices

echo
echo "Enter your choice"
echo
echo "a. date"
echo "b.Present working directory"
echo "c.list of users logged in"
echo "d.Check system uptime"

        read choice
        case $choice in

 a) date ;;
 b) pwd ;;
 c) ls ;;
 d) uptime ;;       
 *) echo "invalid choice bye"

 esac
